<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net8.0;net10.0</TargetFrameworks>
    <Title>OneOf - Easy Discriminated Unions for c#</Title>
    <Description>F# style discriminated unions for C#, using a custom type OneOf&lt;T0, ... Tn&gt; which holds a single value and has a .Match(...) method on it for exhaustive matching. Simple but powerful. Works as a C# 15 union type.</Description>
    <PackageTags>discriminated unions, union types, return type, match switch</PackageTags>
    <PackageId>OneOf</PackageId>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>

    <LangVersion>9.0</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
