<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net8.0;net10.0</TargetFrameworks>
    <Title>OneOf - Easy Discriminated Unions for c#</Title>
    <Description>This package extends the OneOf types from OneOf&lt;T0, .., T9&gt; to OneOf&lt;T0, .., T32&gt; for when you really have a lot of options</Description>
    <PackageTags>discriminated unions, union types, return type, match switch</PackageTags>
    <PackageId>OneOf.Extended</PackageId>
    <RootNamespace>OneOf</RootNamespace>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>

    <LangVersion>9.0</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\OneOf\Polyfills.cs" Link="Polyfills.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OneOf\OneOf.csproj" />
  </ItemGroup>

</Project>
